sudo: required
dist: trusty

language: haxe

haxe:
 - "4.0.5"

install:
 - haxelib git dox https://github.com/HaxeFoundation/dox.git
 - haxelib git heaps https://github.com/HeapsIO/heaps.git
 - haxelib install hxmath
 - haxelib install echo
 - haxelib install ogmo-3
 - haxelib dev ghost .

script:
 - haxe dox.hxml

deploy:
 - provider: pages
   local-dir: bin
   skip-cleanup: true
   github-token: $GITHUB_TOKEN
   on:
    tags: true
 - provider: script
   haxe: "4.0.5"
   script: bash ./release_haxelib.sh $HAXELIB_PWD
   on:
    tags: true
    
