sudo: required
dist: trusty

language: haxe

haxe:
 - "4.0.0-rc.1"

install:
 - haxelib git dox https://github.com/HaxeFoundation/dox.git
 - haxelib git hxmath https://github.com/tbrosman/hxmath.git
 - haxelib git heaps https://github.com/HeapsIO/heaps.git
 - haxelib install ghostlib
 - haxelib install echo
 - haxelib dev ghost .

script:
 - haxe hl.hxml
 - haxe js.hxml
 - haxe dox.hxml

deploy:
 - provider: pages
   local-dir: bin
   skip-cleanup: true
   github-token: $GITHUB_TOKEN
   on:
    tags: true
 - provider: script
   haxe: "4.0.0-rc.1"
   script: bash ./release_haxelib.sh $HAXELIB_PWD
   on:
    tags: true
    
